title:              Linh Tran
email:              linh.ngtran@yahoo.de
description:        M.Sc. Nanoscience Graduate, Scientfic Interest in ML and AI
author:             Linh M. Nguyen Tran
baseurl:            ""
url:                "https://LinhNguyenTran.github.io"

# Social Profiles
twitter_username:   
github_username:    LinhNguyenTran
facebook_username:  
instagram_username:  
linkedin_username: linh-m-nguyen-tran-722b99216

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
